### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shaedrich** [ryangjchandler/lexical#3]
### What happened?

Using the code below, I expected the result to be:
> array(4) {
  [0]=>
  object(Token)#1614 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(5) "Lorem"
  }
  [1]=>
  object(Token)#1620 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Bold)
    ["literal"]=>
    string(5) "**ipsum**"
  }
  [2]=>
  object(Token)#1621 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(1) "t"
  }
  [3]=>
  object(Token)#1616 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(3) "sun"
  }
}

But instead, I got this:
> array(4) {
  [0]=>
  object(Token)#1614 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(5) "Lorem"
  }
  [1]=>
  object(Token)#1620 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(5) "sum**"
  }
  [2]=>
  object(Token)#1621 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(1) "t"
  }
  [3]=>
  object(Token)#1616 (2) {
    ["type"]=>
    enum(BBCodeTokenType::Text)
    ["literal"]=>
    string(3) "sun"
  }
}

Am I doing something wrong here?

### How to reproduce the bug

```
#[Lexer(skip: "[ \t\n\f]+")]
enum MarkdownTokenType
{
    #[Regex("\*\*(.*?)\*\*")]
    case Bold;

    #[Error]
    case Text;
}

class Token
{
    public function __construct(
        public readonly MarkdownTokenType $type,
        public readonly string $literal,
    ) {}
}

$lexer = (new LexicalBuilder)
    ->readTokenTypesFrom(MarkdownTokenType::class)
    ->produceTokenUsing(fn (MarkdownTokenType $type, string $literal) => new Token($type, $literal))
    ->build();
var_dump($lexer->tokenise($request->text));
```

### Package Version

v0.1.0

### PHP Version

8.1.18

### Which operating systems does with happen with?

Linux

**Comment by ryangjchandler** [comment]
Hey @shaedrich - could you try upgrading to v0.1.1 and give it another go? It might not fix the problem but it's worth a go initially.

**Comment by shaedrich** [comment]
Hey Ryan, sure thing! Unfortunately, that didn't solve the problem :/ Dunno, why I was still on the old version despite having it installed only a few days ago after you posted your article on Twitter ^^

If I find the time, I can have a deeper look into your source code and maybe then, I'll have an idea as to what's going on and what doesn't

**Comment by ryangjchandler** [comment]
@shaedrich If you post the sample text you're trying to tokenise I can debug for you :)

**Comment by shaedrich** [comment]
It's not more than this :)
```markdown
Lorem **ipsum** ahmet sun
```

**Comment by ryangjchandler** [comment]
@shaedrich Try upgrading to `v0.1.2` please - I've added your use case as an example in the test suite and can see it working correctly there.

Since you're tokenising Markdown, you might also consider keeping whitespace instead of skipping it. I gave that a go in my tests and realised there was a bug there which has been fixed also, so thank you!

**Comment by shaedrich** [comment]
@ryangjchandler Thanks a lot! That works like a charm :)
